django/conf/project_template/project_name/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

rest_framework/runtests/urls.py
"""
Blank URLConf just to keep runtests.py happy.
"""
from rest_framework.compat import patterns

urlpatterns = patterns('',
)

rest_framework/urls.py
"""
Login and logout views for the browsable API.

Add these to your root URLconf if you're using the browsable API and
your API requires authentication.

The urls must be namespaced as 'rest_framework', and you should make sure
your authentication settings include `SessionAuthentication`.

    urlpatterns = patterns('',
        ...
        url(r'^auth', include('rest_framework.urls', namespace='rest_framework'))
    )
"""
from __future__ import unicode_literals
from rest_framework.compat import patterns, url


template_name = {'template_name': 'rest_framework/login.html'}

urlpatterns = patterns('django.contrib.auth.views',
    url(r'^login/$', 'login', template_name, name='login'),
    url(r'^logout/$', 'logout', template_name, name='logout'),
)

urls.py
"""

    urls.py for non-rel blog.

"""

import os
from django.conf.urls.defaults import *
from django.contrib import admin
import dbindexer
from django.conf import settings 
from django.conf.urls.static import static

handler500 = 'djangotoolbox.errorviews.server_error'

# django admin
admin.autodiscover()

# search for dbindexes.py in all INSTALLED_APPS and load them
dbindexer.autodiscover()

urlpatterns = patterns('',
    (r'^_ah/warmup$', 'djangoappengine.views.warmup'),
    (r'', include('blog.urls')),
) + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS[0]) 

blog/models.py
from django.db import models
from django.utils import timezone
from djangotoolbox.fields import ListField, EmbeddedModelField


class Post(models.Model):
    """
    Basic model for blog posts, includes comments and tags as lists.
    """
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=255)
    permalink = models.CharField(max_length=255, blank=True, null=True)
    user_id = models.IntegerField()
    text = models.TextField()
    tags = ListField(blank=True, null=True)
    comments = ListField(EmbeddedModelField('Comment'), blank=True, null=True)
    created_on = models.DateTimeField(default=timezone.now, blank=True, null=True)
    updated_on = models.DateTimeField(default=timezone.now, blank=True, null=True)
    sticky = models.BooleanField(default=False)

    def create_permalink_from_title(self):
        """
        Create a permalink based on filtering words and whitespaces into underscores.
        Check if there is already and existing one and append _1 or increase the digit
        """
        import re
        exp = re.compile('\W')
        whitespace = re.compile('\s')
        temp_title = whitespace.sub("_", self.title)
        permalink = exp.sub('', temp_title)
        same_permalink = Post.objects.filter(permalink=permalink)
        if same_permalink.count() > 1:
            same_permalink_posts = Post.objects.filter(permalink__startswith=permalink)
            last_permalink = same_permalink_posts[same_permalink_posts.count()-1].permalink
            try:
                index = int(last_permalink[last_permalink.rfind('_')+1:])
                return last_permalink[:last_permalink.rfind('_')+1] + str(index+1)
            except ValueError:
                last_permalink += '_1'
                return last_permalink
        else:
            return permalink

    def save(self, *args, **kwargs):
        self.permalink = self.create_permalink_from_title()
        super(Post, self).save(*args, **kwargs)
    
    def __unicode__(self):
        return '%s - %s ...' % (self.title, self.text[:30].replace('\n', ''))


class Comment(models.Model):
    """
    Comment model, to be included as a list in the Post model.
    """
    author = EmbeddedModelField('Author')
    text = models.TextField()
    created_on = models.DateTimeField(default=timezone.now, blank=True, null=True)

    def __unicode__(self):
        return u'%s: %s' % (self.author.name, self.text[:50] )


class Author(models.Model):
    """
    Author model used in Comments
    """
    name = models.CharField(max_length=255)
    email = models.EmailField()


class SiteActivity(models.Model):
    """
    Information about a certain activity in the site, used in combination with signals.
    """
    user_id = models.IntegerField(blank=True, null=True)
    post_id = models.IntegerField(blank=True, null=True)
    post_title = models.CharField(max_length=255, blank=True, null=True)
    post_permalink = models.CharField(max_length=255, blank=True, null=True)
    created_on = models.DateTimeField(default=timezone.now)

    TASK_CHOICES = (
        ('Created', 'Created a post'),
        ('Updated', 'Updated a post'),
        ('Deleted', 'Deleted a post'),
        ('Comment', 'Commented a post'),
    )
    
    task = models.CharField(max_length=30, choices=TASK_CHOICES, default='Updated')

    def __unicode__(self):
        return u'%s activity on post: %s' % (self.task, self.post_title)

django/contrib/messages/models.py
# Models module required so tests are discovered.

django/contrib/localflavor/generic/forms.py
from django import forms

DEFAULT_DATE_INPUT_FORMATS = (
    '%Y-%m-%d', '%d/%m/%Y', '%d/%m/%y', # '2006-10-25', '25/10/2006', '25/10/06'
    '%b %d %Y', '%b %d, %Y',            # 'Oct 25 2006', 'Oct 25, 2006'
    '%d %b %Y', '%d %b, %Y',            # '25 Oct 2006', '25 Oct, 2006'
    '%B %d %Y', '%B %d, %Y',            # 'October 25 2006', 'October 25, 2006'
    '%d %B %Y', '%d %B, %Y',            # '25 October 2006', '25 October, 2006'
)

DEFAULT_DATETIME_INPUT_FORMATS = (
    '%Y-%m-%d %H:%M:%S',     # '2006-10-25 14:30:59'
    '%Y-%m-%d %H:%M',        # '2006-10-25 14:30'
    '%Y-%m-%d',              # '2006-10-25'
    '%d/%m/%Y %H:%M:%S',     # '25/10/2006 14:30:59'
    '%d/%m/%Y %H:%M',        # '25/10/2006 14:30'
    '%d/%m/%Y',              # '25/10/2006'
    '%d/%m/%y %H:%M:%S',     # '25/10/06 14:30:59'
    '%d/%m/%y %H:%M',        # '25/10/06 14:30'
    '%d/%m/%y',              # '25/10/06'
)

class DateField(forms.DateField):
    """
    A date input field which uses non-US date input formats by default.
    """
    def __init__(self, input_formats=None, *args, **kwargs):
        input_formats = input_formats or DEFAULT_DATE_INPUT_FORMATS
        super(DateField, self).__init__(input_formats=input_formats, *args, **kwargs)

class DateTimeField(forms.DateTimeField):
    """
    A date and time input field which uses non-US date and time input formats
    by default.
    """
    def __init__(self, input_formats=None, *args, **kwargs):
        input_formats = input_formats or DEFAULT_DATETIME_INPUT_FORMATS
        super(DateTimeField, self).__init__(input_formats=input_formats, *args, **kwargs)

class SplitDateTimeField(forms.SplitDateTimeField):
    """
    Split date and time input fields which use non-US date and time input
    formats by default.
    """
    def __init__(self, input_date_formats=None, input_time_formats=None, *args, **kwargs):
        input_date_formats = input_date_formats or DEFAULT_DATE_INPUT_FORMATS
        super(SplitDateTimeField, self).__init__(input_date_formats=input_date_formats,
                                                 input_time_formats=input_time_formats, *args, **kwargs)

search/forms.py
from django import forms

class LiveSearchField(forms.CharField):
    def __init__(self, src, multiple_values=False, select_first=False,
                 auto_fill=False, must_match=False, match_contains=True,
                 **kwargs):
        attrs = {'src': src}
        classes = []
        if multiple_values:
            classes.append('multiple-values')
        if select_first:
            classes.append('select-first')
        if auto_fill:
            classes.append('auto-fill')
        elif match_contains:
            classes.append('match-contains')
        if must_match:
            classes.append('must-match')
        if classes:
            attrs['class'] = ' '.join(classes)
        super(LiveSearchField, self).__init__(
            widget=forms.TextInput(attrs=attrs), **kwargs)

search/views.py
from django.conf import settings
from djangotoolbox.http import JSONResponse

def live_search_results(request, model, search_index='search_index', limit=30,
        result_item_formatting=None, query_converter=None,
        converter=None, redirect=False):
    """
    Performs a search in searched_model and prints the results as
    text, so it can be used by auto-complete scripts.

    limit indicates the number of results to be returned.

    A JSON file is sent to the browser. It contains a list of
    objects that are created by the function indicated by
    the parameter result_item_formatting. It is executed for every result
    item.
    Example:
    result_item_formatting=lambda course: {
        'value': course.name + '<br />Prof: ' + course.prof.name,
        'result': course.name + ' ' + course.prof.name,
        'data': redirect=='redirect' and
            {'link': course.get_absolute_url()} or {},
    }
    """
    query = request.GET.get('query', '')
    try:
        limit_override = int(request.GET.get('limit', limit))
        if limit_override < limit:
            limit = limit_override
    except:
        pass
    search_index = getattr(model, search_index)
    language = getattr(request, 'LANGUAGE_CODE', settings.LANGUAGE_CODE)
    results = search_index.search(query, language=language)
    if query_converter:
        results = query_converter(request, results)
    results = results[:limit]
    if converter:
        results = converter(results)
    data = []
    for item in results:
        if result_item_formatting:
            entry = result_item_formatting(item)
        else:
            value = getattr(item, search_index.fields_to_index[0])
            entry = {'value': force_escape(value), 'result': value}
        if 'data' not in entry:
            entry['data'] = {}
        if redirect:
            if 'link' not in entry['data']:
                entry['data']['link'] = item.get_absolute_url()
        data.append(entry)
    return JSONResponse(data)

templates/backbone_base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="user_id" content="{{user.id}}">
        <title>{% block title %}{% endblock %} NonRel Blog</title>
        <link rel="stylesheet" type="text/css" href="/static/bootstrap/css/bootstrap.min.css" />
        <link rel="stylesheet" type="text/css" href="/static/nonrel-blog.css" />
    </head>
    <body>
        <header>
        <div class="navbar navbar-inverse navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/#">NonRel Blog</a>
            </div>
            <div class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                  {% if not user.is_authenticated %}
                  <li><a href="/login">Login</a></li>
                  <li><a href="/register">Register</a></li>
                  {% else %}
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.username }} <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li><a href="/create_post" id="create-new-post">Create new post</a></li>
                      <li><a href="/logout">Logout</a></li>
                    </ul>
                  </li>
                  <noscript>
                  <li><a href="/create_post" id="create-new-post">Create new post</a></li>
                  <li><a href="/logout">Logout</a></li>
                  </noscript>
                  {% endif %}
              </ul>
            <form class="navbar-form navbar-right" action="/search/" method="get">
            <div class="input-group">
                <input type="text" placeholder="Search..." name="q" class="form-control" />
                <span class="input-group-btn">
                <button class="btn btn-default" type="button" onclick="$('.navbar-form').submit();">
                    <span class="glyphicon glyphicon-search"></span>
                </button>
                </span>
            </div>
            </form>
            </div><!--/.nav-collapse -->
          </div>
        </div>
        </header>
        <div id="site-activity"></div>
        <div id="main" class="starter-template">
        {% block content %}{% endblock %}
        </div>
        <!-- end main div -->
        <script id="postListTemplate" type="text/template">
            <h2><a href="#post/<%= permalink %>"><%= title %></a></h2>
            <% if (tags != null && tags.length > 0) { %>
                <div class="tags">
                <% _.each(tags, function(tag) { %>
                <a href="#tag/<%- tag %>"><button type="button" class="btn btn-default btn-xs"><%= tag %></button></a>
                <% }); %>
                </div>
            <% } %></p>
            <p>by <strong><a href="#user/<%= user_name %>"><%= user_name %></a></strong> on <small><strong><%= updated_on_readable %></strong></small>
            <p><%= snippetText %>...</p>
            <p class="right-italic"><% if(comments != null) {print(comments.length);}else{print(0);} %> comments</p>
        </script>
        <script id="postTemplate" type="text/template">
            <h1><%= title %></h1>
            <% try {
                 if (skipEditButtons) {}
               } catch(e) {
                    if ( user_id == $('meta[name="user_id"]').attr('content')) { %>
                        <div id="admin-buttons" class="pull-right">
                            <a href="#post/<%= permalink %>/edit" class="btn btn-primary btn-xs">Edit post</a>
                            <a id="delete-post" class="btn btn-primary btn-xs">Delete post</a>
                        </div>
               <%
                  }
               }
               if (tags != null && tags.length > 0) { %>
                <div class="tags">
                <% _.each(tags, function(tag) { %>
                <a href="#tag/<%= tag %>"><button type="button" class="btn btn-default btn-xs"><%= tag %></button></a>
                <% }); %>
                </div>
            <% } %>
            <p class="date">Posted by <a href="#user/<%= user_name %>"><%= user_name %></a> on <%= updated_on_readable %></p>
            <p><%= text %></p>
            <% try { if(skipCommentsForm) { %> <hr/> <% } } catch(e) { %>
            <div id="comment-section">
            <% if (comments != null && comments.length > 0) { %>
                <% _.each(comments, function(item, index) { %>
                <div class="comment<% if (index % 2 == 0) { %> even <% } else { %> odd <% } %>">
                    <p><%- item.text %></p>
                    <p class="text-right"><small>by <%- item.author.name %> - <%- item.author.email %><br />on <%- item.created_on_readable %></small></p>
                </div>
                <% }); %>
            <% }else{ %>
                <h3>No comments</h3>
            <% } %>
                <hr/>
                <p>Add a comment:</p>
                <div class="fieldWrapper form-group">
                    <label for="id_name">Name:</label>
                    <input id="id_name" class="form-control input-sm" type="text" placeholder="Your Name" maxlength="255" name="name"></input>
                </div>
                <div class="fieldWrapper form-group">
                    <label for="id_email">Email:</label>
                    <input id="id_email" class="form-control input-sm" type="text" placeholder="you@example.org" maxlength="75" name="email"></input>
                </div>
                <div class="fieldWrapper form-group">
                    <label for="id_text">Comment:</label>
                    <textarea id="id_text" class="form-control input-sm" cols="80" placeholder="Your comment ..." name="text" rows="10"></textarea>
                </div>
                <p><input type="submit" value="Submit comment" class="btn btn-primary" id="comment-submit" /></p>
            <% } %>
            </div>
        </script>
        <script id="loadMoreTemplate" type="text/template">
            <p class="text-center"><a id="load-more-posts" class="btn btn-primary">Load more posts...</a></p>
        </script>
        <script id="formErrorTemplate" type="text/template">
            <div class="alert alert-danger alert-dismissable">
                <button class="close" aria-hidden="true" data-dismiss="alert" type="button">×</button>
                <ul class="list-group">
                    <div class="error"><%- error_msg %></div>
                </ul>
            </div>
        </script>
        <script id="confirmDeletionTemplate" type="text/template">
            <div class="alert alert-danger fade in">
                <button class="close" aria-hidden="true" data-dismiss="alert" type="button"> × </button>
                <h3>Are you sure you want to delete this post?
                <button class="btn btn-danger" type="button" id="delete-yes">Yes</button>
                <button class="btn" type="button" id="delete-no">No</button>
                </h3>
            </div>
        </script>
        <script id="postFormTemplate" type="text/template">
            <h1><%= mode %> post:</h1>
            <div id="post-preview"></div>
            <div class="fieldWrapper form-group">
                <label for="post-title">Title</label>
                <input id="post-title" class="form-control input-sm" type="text" name="title" maxlength="255" placeholder="Title for your post" value="<%= title %>" autofocus></input>
            </div>
            <div class="fieldWrapper form-group">
                <label for="post-text">Text</label>
                <textarea id="post-text" class="form-control input-sm" placeholder="Your post here..." cols="80" name="text" rows="20"><%= text %></textarea>
                <span class="help-block">Accepted tags are <strong>a</strong>, <strong>b</strong>, <strong>strong</strong>, <strong>i</strong>, <strong>em</strong>, <strong>ol</strong>, <strong>ul</strong> and  <strong>li</strong>. All other tags will be removed.</span>
            </div>
            <div class="fieldWrapper form-group">
                <label for="post-tags">Tags</label>
                <input id="post-tags" class="form-control input-sm" type="text" name="tags" maxlength="255" placeholder="tag1 tag2 tag3" value="<% print(tags.join(' ')); %>"></input>
            </div>
            <p>
                <button class="btn btn-primary" id="preview-post">Preview</button>
                <button class="btn btn-primary" type="submit" id="submit-post"><%= mode %> post</button>
            </p>
            </div>
        </script>
        <script id="activityTemplate" type="text/template">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            <% if (task != 'Deleted') { %>
            <%= task %> post <a href="#post/<%= post_permalink %>" class="alert-link"><%= post_title %></a>
            <% } else { %>
            <%= task %> post <%= post_title %>
            <% } %>
        </script>
        <script id="uniqueTagTemplate" type="text/template">
            <button id="tag-<%= cid %>" type="button" class="btn btn-default btn-xs tag-suggestion"><%= name %></button>
        </script>
        <script type="text/javascript" src="/static/js/lib/jquery-1.11.0.js"></script>
        <script type="text/javascript" src="/static/js/lib/underscore.js"></script>
        <script type="text/javascript" src="/static/js/lib/backbone.js"></script>
        <script type="text/javascript" src="/static/bootstrap/js/bootstrap.min.js"></script>
        <script type="text/javascript" src="/static/js/routers/router.js"></script>
        <script type="text/javascript" src="/static/js/models/post.js"></script>
        <script type="text/javascript" src="/static/js/collections/blog.js"></script>
        <script type="text/javascript" src="/static/js/models/siteactivity.js"></script>
        <script type="text/javascript" src="/static/js/collections/siteactivities.js"></script>
        <script type="text/javascript" src="/static/js/models/tag.js"></script>
        <script type="text/javascript" src="/static/js/collections/uniqueTags.js"></script>
        <script type="text/javascript" src="/static/js/views/postList.js"></script>
        <script type="text/javascript" src="/static/js/views/post.js"></script>
        <script type="text/javascript" src="/static/js/views/createPost.js"></script>
        <script type="text/javascript" src="/static/js/views/blog.js"></script>
        <script type="text/javascript" src="/static/js/views/siteActivity.js"></script>
        <script type="text/javascript" src="/static/js/views/tagSuggestionView.js"></script>
        <script type="text/javascript" src="/static/js/app.js"></script>
        {% block backbone_init %}{% endblock %}
    </body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %} NonRel Blog</title>
        <link rel="stylesheet" type="text/css" href="/static/bootstrap/css/bootstrap.min.css" />
        <link rel="stylesheet" type="text/css" href="/static/nonrel-blog.css" />
    </head>
    <body>
        <header>
        <div class="navbar navbar-inverse navbar-fixed-top">
          <div class="container">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/">NonRel Blog</a>
            </div>
            <div class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                  {% if not user.is_authenticated %}
                  <li><a href="/login">Login</a></li>
                  <li><a href="/register">Register</a></li>
                  {% else %}
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.username }} <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                      <li><a href="/create_post">Create new post</a></li>
                      <li><a href="/logout">Logout</a></li>
                    </ul>
                  {% endif %}
              </ul>
            <form class="navbar-form navbar-right" action="/search/" method="get">
            <div class="input-group">
                <input type="text" placeholder="Search..." name="q" class="form-control" />
                <span class="input-group-btn">
                <button class="btn btn-default" type="button" onclick="$('.navbar-form').submit();">
                    <span class="glyphicon glyphicon-search"></span>
                </button>
                </span>
            </div>
            </form>
            </div><!--/.nav-collapse -->
          </div>
        </div>
        </header>
        <div id="main" class="starter-template">
        {% block content %}{% endblock %}
        </div>
        <!-- end main div -->
        <script type="text/javascript" src="/static/js/lib/jquery-1.11.0.min.js"></script>
        <script type="text/javascript" src="/static/bootstrap/js/bootstrap.min.js"></script>
    </body>
</html>

templates/create_post.html
{% extends "backbone_base.html" %}
{% block title %}Create post{% endblock %}
{% block content %}
<h3>Create new post:</h3>
<form action="/create_post" method="post">{% csrf_token %}
{% include "generic_form.html" %}
<p><input type="submit" value="Create post" class="btn btn-primary" id="submit" /></p>
{% endblock %}

templates/delete_post.html
{% extends "backbone_base.html" %}
{% block title %}Delete post{% endblock %}
{% block content %}
<h3>Delete post:</h3>
{% if error %}
	<div class="alert alert-danger">{{ result }}</div>
{% else %}
	{{ result }}
{% endif %}
<p><a href="/" class="btn btn-primary">Latest posts</a></p>
{% endblock %}

templates/edit_post.html
{% extends "backbone_base.html" %}
{% block title %}Edit post{% endblock %}
{% block content %}
{% include "messages.html" %}
{% if not error %}
	<h3>Edit post:</h3>
	<div id="post-preview"></div>
	<form action="" method="post">{% csrf_token %}
	{% include "generic_form.html" %}
	<p><input type="submit" value="Edit post" class="btn btn-primary" id="submit" /></p>
	<script src="/static/js/post_preview.js" type="text/javascript"></script>
{% else %}
	<div class="alert alert-danger">{{ result }}</div>
{% endif %}
{% endblock %}

templates/generic_form.html
{% for field in form %}
	{{ field.media }}
    <div class="fieldWrapper form-group{% if field.errors %} has-error{% endif %}">
    	{% if field.as_p %}
    		{{ field.label_tag.as_p }}{{ field.as_p }}
        {% else %}
        	{{ field.label_tag }}{{ field }}
        {% endif %}
        {% if field.help_text %}<span class="help-block">{{ field.help_text }}</span>{% endif %}
        {% if field.errors %}{% autoescape off %}{{ field.errors }}{% endautoescape %}{% endif %}
    </div>
{% endfor %}

templates/home.html
{% extends "backbone_base.html" %}
{% block title %}Latest posts{% endblock %}
{% block content %}
<noscript>
{% include "messages.html" %}
<h1>Welcome{% if user.is_authenticated %} {{ user.username }}{% endif %}! Here are the latest posts:</h1>
{% if posts %}
<div id="post-list">
    {% include "post_list.html" %}
</div>
{% else %}
    <h2>Sorry, no posts in database.</h2>
{% endif %}
</noscript>
{% endblock %}
{% block backbone_init %}
{% autoescape off %}
    <script type="text/javascript">
        $(function() {
            var _sync = Backbone.sync;
            Backbone.sync = function(method, model, options){
                options.beforeSend = function(xhr){
                    xhr.setRequestHeader('X-CSRFToken', '{{ csrf_token }}');
                };
                return _sync(method, model, options);
            };
            app.csrf_token = '{{ csrf_token }}';

            // in order to preserve no JS functionality we change the the create new post link on load to a hash.
            if ($('#create-new-post')[0] != undefined) {
                $('#create-new-post')[0].pathname = ''
                $('#create-new-post')[0].hash = 'create_post'
            }
            // start up the components
            app.blogCollection = new app.BlogCollection();
            app.uniqueTagsCollection = new app.UniqueTagsCollection();
            app.blogRouter = new Workspace();
            app.blogView = new app.BlogView({collection: app.blogCollection});
            app.siteActivitiesCollection = new app.SiteActivitiesCollection();
            app.siteActivitiesView = new app.SiteActivitiesView({collection: app.siteActivitiesCollection});
            Backbone.history.start();
            // bootstrap initial models from Django if loading the home page.
            if (window.app && window.location.hash === '') {
                app.blogCollection.next = '{{ next }}';
                app.blogCollection.count = {{ total_posts }};
                app.blogCollection.reset({{ models_json }});
            }else{
                // retrieve the route and navigate otherwise
                var route = window.location.hash.substring(1);
                app.blogRouter.navigate(route, {trigger: true, replace: true});
            }
        });
    </script>
{% endautoescape %}
{% endblock %}

templates/login.html
{% extends "backbone_base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
<div id="login">
{% if login_failed %}
	<div class="alert alert-danger">The username of password are not recognized.</div>
{% endif %}
<form action="/login" method="post">{% csrf_token %}
{% include "generic_form.html" %}
<p><input type="submit" value="Login" class="btn btn-primary" /></p>
</div>
{% endblock %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
    <div class="alert{% if message.tags %} alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
{% endif %}

templates/register.html
{% extends "backbone_base.html" %}
{% block title %}Register{% endblock %}
{% block content %}
<div id="login">
<form action="/register" method="post">{% csrf_token %}
{% include "generic_form.html" %}
<p><input type="submit" value="Register" class="btn btn-primary" /></p>
</div>
{% endblock %}

templates/search.html
{% extends "backbone_base.html" %}
{% block title %}Posts matching {{ terms }}{% endblock %}
{% block content %}
<h1>Results matching "{{ terms }}":</h1>
{% if posts %}
<div id="post-list">
	{% include "post_list.html" %}
</div>
	{% if posts|length < total_posts %}
		{% include "load_more_posts.html" with page="search" %}
	{% endif %}
{% else %}
	<h2>Sorry, no posts match that query.</h2>
{% endif %}
{% endblock %}

templates/tag_buttons.html
{% if post.tags %}
<div class="tags">
{% for tag in post.tags %}
<a href="/tag/{{tag}}"><button type="button" class="btn btn-default btn-xs">{{ tag }}</button></a>	
{% endfor %}
</div>
{% endif %}	